name: CI - Test and Coverage

on:
  # 当推送到任何分支时触发
  push:
    branches: ["**"]
  # 当有PR时触发
  pull_request:
    branches: ["main"]
  # 允许手动触发
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        with:
          fetch-depth: 2
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Run Biome checks
        run: pnpm run check

      - name: Run tests with coverage
        run: pnpm run coverage:ci

      - name: Build example
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
          GH_COMMIT_SHA: ${{ github.event.pull_request.head.sha }}
        run: pnpm run build-example

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: yourtion/lynx-html-renderer

      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
